<Project>
  <PropertyGroup>
	<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
	<PackageVersion Include="ClickHouse.Client" Version="7.14.0" />
	<PackageVersion Include="coverlet.collector" Version="6.0.4" />
	<PackageVersion Include="Immediate.Apis" Version="6.2.0" />
	<PackageVersion Include="Immediate.Handlers" Version="4.0.0" />
	<PackageVersion Include="Immediate.Injections" Version="1.0.0" />
	<PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.19" />
	<PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.19" />
	<PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.19" />
	<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
	<PackageVersion Include="NodaTime" Version="3.2.2" />
	<PackageVersion Include="NodaTime.Serialization.SystemTextJson" Version="1.4.0" />
	<PackageVersion Include="NodaTime.Testing" Version="3.2.2" />
	<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
	<PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.NodaTime" Version="8.0.11" />
	<PackageVersion Include="Refit" Version="8.0.0" />
	<PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
	<PackageVersion Include="Serilog.Enrichers.Environment" Version="3.0.1" />
	<PackageVersion Include="Serilog.Enrichers.Thread" Version="4.0.0" />
	<PackageVersion Include="Serilog.Exceptions" Version="8.4.0" />
	<PackageVersion Include="xunit" Version="2.9.3" />
	<PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
	<GlobalPackageReference Include="Meziantou.Analyzer" Version="2.0.189" />
	<GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="3.3.4" PrivateAssets="all" />
	<AdditionalFiles Include="$(MSBuildThisFileDirectory)docs/guidelines/BannedSymbols.txt" />
  </ItemGroup>
</Project>
